apiVersion: v1
kind: Service
metadata:
  name: digit-hcm-frontend
  namespace: digit-hcm
  labels:
    app: digit-hcm
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: digit-hcm
    tier: frontend