apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digit-hcm-backend-pdb
  namespace: digit-hcm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: digit-hcm
      tier: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digit-hcm-frontend-pdb
  namespace: digit-hcm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: digit-hcm
      tier: frontend