apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-hcm-data
  namespace: digit-hcm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-hcm-logs
  namespace: digit-hcm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-hcm-uploads
  namespace: digit-hcm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 100Gi