apiVersion: v1
kind: ServiceAccount
metadata:
  name: digit-hcm-sa
  namespace: digit-hcm
  annotations:
    eks.amazonaws.com/role-arn: "${SERVICE_ACCOUNT_ROLE_ARN}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: digit-hcm-role
  namespace: digit-hcm
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: digit-hcm-role-binding
  namespace: digit-hcm
subjects:
  - kind: ServiceAccount
    name: digit-hcm-sa
    namespace: digit-hcm
roleRef:
  kind: Role
  name: digit-hcm-role
  apiGroup: rbac.authorization.k8s.io